name: CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/ec2-key.pem

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem admin@${{ secrets.EC2_HOST }} << 'EOF'
          cd /BDLabs
          git pull origin main
          docker build -t lab1:${{ github.sha }} .
          docker stop lab1_app || true
          docker rm lab1_app || true
          docker run -d --name lab1_app -p 5000:5000 lab1:${{ github.sha }}
          EOF